### PR TITLE
Start of conversion to .toURI()

### PR DESCRIPTION
**Pull request by stevendlander**
http://stackoverflow.com/a/7700072/613748

Don't use `.getAbsolutePath()` as it can break when a path has spaces.

---
This change is [Reviewable](https://reviewable.io/reviews/githubrgi/swagd/371)

### CODE REVIEW

**Comment by stevendlander** [comment]
Clarification:

A `URI` should be used with database connection strings, and a `Path` should be fine for everything else.

**Comment by moran0013** [comment]
Reviewed 2 of 2 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Common/src/test/java/com/rgi/common/util/jdbc/JdbcUtilityTest.java, line 34 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDve4pPbxBRXnh9mHD:-KGDve4pPbxBRXnh9mHE:988285068) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/Common/src/test/java/com/rgi/common/util/jdbc/JdbcUtilityTest.java#L34)):*
should import specific modules. 

---

*[DataStore/src/main/java/com/rgi/store/tiles/geopackage/GeoPackageWriter.java, line 133 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDw3Qw578DSQc8ZJW-:-KGDw3Qw578DSQc8ZJW0:-973874615) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/DataStore/src/main/java/com/rgi/store/tiles/geopackage/GeoPackageWriter.java#L133)):*
File URI may lead to some confusing output for users, we may want to format the uri to a more human readable format (they will be expecting "C:\yadda yadda"

---

*[GeoPackage/src/test/java/com/rgi/geopackage/DatabaseUtilityTest.java, line 66 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDwN-mPH3NoNLLqCuL:-KGDwN-mPH3NoNLLqCuM:1505849532) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/GeoPackage/src/test/java/com/rgi/geopackage/DatabaseUtilityTest.java#L66)):*
i know this will autoclose the connection, but will it delete the temp file as well?

---

*[GeoPackage/src/test/java/com/rgi/geopackage/DatabaseUtilityTest.java, line 85 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDwUzSYHypcBmVr8It:-KGDwUzSYHypcBmVr8Iu:-1563071082) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/GeoPackage/src/test/java/com/rgi/geopackage/DatabaseUtilityTest.java#L85)):*
same as above, is the temp file deleted when the connection is closed?

---

*[GeoPackage/src/test/java/com/rgi/geopackage/GeoPackageTilesAPITest.java, line 184 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDx453hGum1VT-UX7f:-KGDx454e353HoLUFzFU:658811836) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/GeoPackage/src/test/java/com/rgi/geopackage/GeoPackageTilesAPITest.java#L184)):*
is testFile global? (reviewable doesnt show item instantiation)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/githubrgi/swagd/371)*

**Comment by stevendlander** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[DataStore/src/main/java/com/rgi/store/tiles/geopackage/GeoPackageWriter.java, line 133 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDw3Qw578DSQc8ZJW-:-KGE-_HuwrEtgQDJft8A:1793411313) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/DataStore/src/main/java/com/rgi/store/tiles/geopackage/GeoPackageWriter.java#L133)):*
Reverting back to `getPath()`

---

*[GeoPackage/src/test/java/com/rgi/geopackage/DatabaseUtilityTest.java, line 66 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDwN-mPH3NoNLLqCuL:-KGE-iB0nJ_udOSl_uYn:160424898) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/GeoPackage/src/test/java/com/rgi/geopackage/DatabaseUtilityTest.java#L66)):*
yes

---

*[GeoPackage/src/test/java/com/rgi/geopackage/DatabaseUtilityTest.java, line 85 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDwUzSYHypcBmVr8It:-KGE-irFlG5ygDxvY7p8:1252055662) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/GeoPackage/src/test/java/com/rgi/geopackage/DatabaseUtilityTest.java#L85)):*
yes as well, see TestUtility.getRandomFile().  The file will delete itself once the JVM exits.

---

*[GeoPackage/src/test/java/com/rgi/geopackage/GeoPackageTilesAPITest.java, line 184 \[r2\]](https://reviewable.io:443/reviews/githubrgi/swagd/371#-KGDx453hGum1VT-UX7f:-KGE01vXySCZsTiaxqdu:1777693596) ([raw file](https://github.com/githubrgi/swagd/blob/049c2cb545c0947c0b28ae7e9021577e0de4bb9f/GeoPackage/src/test/java/com/rgi/geopackage/GeoPackageTilesAPITest.java#L184)):*
no, testFile is just in that test function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/githubrgi/swagd/371)*

**Comment by moran0013** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/githubrgi/swagd/371)*

**Pull request merged**
